//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class CommonStand : BaseStatus
{
    public override void UpdateLogic ()
    {
		
    }
	
    public override STATUS GetNextStatus ()
    {
        return STATUS.NONE;
    }
}